/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MPN */

#ifndef _Included_MPN
#define _Included_MPN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MPN
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MPN_main
  (JNIEnv *, jobject);

/*
 * Class:     MPN
 * Method:    getMPN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MPN_getMPN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
